= Editor’s note

// == _Why this version of the standard?_

The http://inform-fiction.org/zmachine/standards/z1point1[existing and canonical HTML version of _The Z-Machine Standards Document_] is a good reference, and contains invaluable information about the structure and functioning of a Z-machine interpreter. But, in the process of using it to write my own interpreter implementation, I found that (a) jumping back and forth between sections was awkward without an in-page table of contents{empty}footnote:[Technically, there _is_ a brief table of contents of sorts at the bottom of every page in the canonical docs, but the sections and appendices listed therein are _only_ given numbers and letters; unless you’ve memorized which section is which, it’s only usable for manually navigating the numbered cross-section links!], (b) the formatting—or lack thereof—made it less legible than it could be, and (c) there were some technical details that seemed to be assumed rather than made explicit.

To that end, I decided to convert the document to a more-modern presentation, and also annotate it with additional information I discovered in the process. (This might also serve as the initial source for an entirely new document, restructured for an interpreter-writing audience.)

None of this would exist without the tireless work of Graham Nelson and the other intrepid code spelunkers (see xref:001-preface.adoc[the original preface]) that reverse-engineered the format and logic of the original Infocom game files.


_Jared Reisinger_ +
_3 February 2022_
