= Conventions used in this document
:idprefix:

The original http://inform-fiction.org/zmachine/standards/z1point1[_The Z-Machine Standards Document_] used very little in the way of formatting, only a little *bold* to highlight keywords and values, and _italics_ for emphasis.  This version is far more liberal with formatting, using:

- *bold* for keywords and programs/tools/packages

- _italics_ for emphasis or citations

- `monospace` for exact command lines or code samples

- `*bold monospace*` for opcodes

- tables for tabular data that previously used monospace/“pre” for rendering

- hyperlinks have been added for cross-section references (rather than just refering to “**S*1.1″, say, it's now “xref:01-memory-map.adoc#1-1[*S**1.1]″)

- text adventure game names are _italicized like a book title_ rather than ‘quoted’, purely to make the resulting text prettier

- _M_._N_ sections are given names from the _M_ contents at the top of the page

[NOTE]
.This is no longer true.
====
In that the source document for this is Markdown, lengthy code samples will probably _not_ have in-sample formatting... but if I can figure out how to do syntax coloring, that may be added as well.
====


The spelling in the original document uses British English for the most part, and no spelling changes have been made.  The annotations are generally in American English.

When significant commentary is made, it will be in a “sidebar”, shown as:

.This is a sidebar
****
It might contain just a quick note, or maybe a long monograph.

====
This is an example inside the sidebar.
====
****
