= Opcodes revisited

I personally found the xref:14-opcode-table[opcode tables] very hard to interpret, despite the xref:14-opcode-table.adoc#reading_the_opcode_tables[section that tries to explain things]. After looking at some output from *Txd*, however, the tables make a little more sense… but they are still (to me) awkwardly constructed, not easy to interpret, and not exhaustive.

Further, xref:04-instructions.adoc[**S**4] delves into how the bitfields in an opcode should be interpreted, but then the tables in xref:14-opcode-table.adoc[**S**14] _don’t_ list the instructions by opcode number, instead (kind of?) falling back to the raw opcode value. This raises the question whether the opcode number really has any meaning or not. Through some trial-and-error, I’ve determined that xref:04-instructions.adoc#4_3[“opcode number” as defined in **S**4.3] is not sufficient in and of itself to define a Z-Machine instruction. Why? Because instructions often require a particular number of operands, and more than one of the operand-count values (0OP, 1OP, 2OP, VAR) can have the same “opcode number” value. Further, because the two high-bits of the opcode define the _form_ and not the operand count—and in fact the operand count might be implied by form and operand type!—it is not at all trivial to describe “what does instruction _xxx_ look like?” both concisely *_and_* completely.

When trying to author an interpreter, however, you very much need to know how to answer that question. To that end, what follows is a re-creation of the opcode tables, keyed off the operand count (or form for extended opcodes!) and opcode number, but with *_every_* variant listed explicitly. Although the table below uses *Count* as a header, it’s also used for “EXT” for extended opcode instructions. The original tables started with 2OP, but I believe that was an unexplicit side-effect of `${empty}$00`-prefixed opcodes being long-form 2OP ones. Since there will necessarily be an intermingling of opcode value (to keep like opcode _numbers_ together), this list uses the order 0OP, 1OP, 2OP, VAR, EXT. In this table, *Num* is the opcode number, and should represent *_an_* instruction in the context of a particular *Count* (with the caveat that it might change across Z-machine versions). The *Dec.*, *Hex*, and *Binary* columns are the _complete_ opcode value, to aid in looking at hex dumps and writing an interpreter. (For the original table’s __TYPE__:__Decimal__ identifiers, look at *__Count__:__Decimal__* here.)  The *Form* and *Args* (operands with a shorter label!) columns are abbreviated to S,L,V,E for Short, Long, Variable, and Extended for the form, and als to S,L,V for each operand for Small constant, Large constant, and Variable.  Also, note that per-version variations might _look_ like they are specific to particular decimal/hex opcodes, but they typically aren't; Rather than duplicate the entire set of opcodes for multi-variant instructions, they are only listed once (see 1OP:15 as an example).  Truly, both the decimal/hex/binary/form/operand-types and the per-version instruction variations should be thought of as orthogonal nested tables, but the layout is already rather complex.

[cols="1,>1,>1,1,3,1,1,^1,^1,^1,25", frame=none, grid=rows]
|===
   |Count   |Num      |Dec.    |Hex     |Binary        |Form   | Args  | V |St |Br | Instruction and syntax

11+| *_0OP opcodes_*
   |0OP     |  0      |176     |`b0`    |`10110000`    |S      |       |   |   |   | xref:15-opcodes.adoc#rtrue[`*rtrue*`]
   |0OP     |  1      |177     |`b1`    |`10110001`    |S      |       |   |   |   | xref:15-opcodes.adoc#rfalse[`*rfalse*`]
   |0OP     |  2      |178     |`b2`    |`10110010`    |S      |       |   |   |   | xref:15-opcodes.adoc#print[`*print*`] (literal string)
   |0OP     |  3      |179     |`b3`    |`10110011`    |S      |       |   |   |   | xref:15-opcodes.adoc#print_ret[`*print_ret*`] (literal string)
   |0OP     |  4      |180     |`b4`    |`10110100`    |S      |       |1/-|   |   | xref:15-opcodes.adoc#nop[`*nop*`]
.3+|0OP  .3+|  5   .3+|181  .3+|`b5` .3+|`10110101` .3+|S   .3+|       | 1 |   | * | xref:15-opcodes.adoc#save[`*save*`] ?(label)
                                                                      ^| 4 |   |   | xref:15-opcodes.adoc#save[`*save*`] -> (result)
                                                                      ^| 5 |   |   | _illegal_
.3+|0OP  .3+|  6   .3+|182  .3+|`b6` .3+|`10110110` .3+|S   .3+|       | 1 |   | * | xref:15-opcodes.adoc#restore[`*restore*`] ?(label)
                                                                      ^| 4 |   |   | xref:15-opcodes.adoc#restore[`*restore*`] -> (result)
                                                                      ^| 5 |   |   | _illegal_
   |0OP     |  7      |183     |`b7`    |`10110111`    |S      |       |   |   |   | xref:15-opcodes.adoc#restart[`*restart*`]
   |0OP     |  8      |184     |`b8`    |`10111000`    |S      |       |   |   |   | xref:15-opcodes.adoc#ret_popped[`*ret_popped*`]
.2+|0OP  .2+|  9   .2+|185  .2+|`b9` .2+|`10111001` .2+|S   .2+|       | 1 |   |   | xref:15-opcodes.adoc#pop[`*pop*`]
                                                                      ^|5/6| * |   | xref:15-opcodes.adoc#catch[`*catch*`] -> (result)
   |0OP     | 10      |186     |`ba`    |`10111010`    |S      |       |   |   |   | xref:15-opcodes.adoc#quit[`*quit*`]
   |0OP     | 11      |187     |`bb`    |`10111011`    |S      |       |   |   |   | xref:15-opcodes.adoc#new_line[`*new_line*`]
.2+|0OP  .2+| 12   .2+|188  .2+|`bc` .2+|`10111100` .2+|S   .2+|       | 3 |   |   | xref:15-opcodes.adoc#show_status[`*show_status*`]
                                                                      ^| 4 |   |   | _illegal_
   |0OP     | 13      |189     |`bd`    |`10111101`    |S      |       | 3 |   |   | xref:15-opcodes.adoc#verify[`*verify*`] ?(label)
11+| _0OP:14 is 190 (`0xbe`), the first byte for an extended opcode (see EXT)_
   |0OP     | 15      |191     |`bf`    |`10111111`    |S      |       |5/-|   |   | xref:15-opcodes.adoc#piracy[`*piracy*`]
11+| *_1OP opcodes_*
   |*Count* |*Num*    |*Dec.*  |*Hex*   |*Binary*     |*Form*|*Args*  |*V*|*St*|*Br*|*Instruction and syntax*
.3+|1OP  .3+|  0      |128     |`80`    |`10000000`    |S     |L    .3+|   .3+|   .3+| * .3+| xref:15-opcodes.adoc#jz[`*jz*`] a ?(label)
                     >|144    <|`90`    |`10010000`    |S     |S
                     >|160    <|`a0`    |`10100000`    |S     |V
.3+|1OP  .3+|  1      |129     |`81`    |`10000001`    |S     |L    .3+|   .3+| * .3+| * .3+| xref:15-opcodes.adoc#get_sibling[`*get_sibling*`] object -> (result) ?(label)
                     >|145    <|`91`    |`10010001`    |S     |S
                     >|161    <|`a1`    |`10100001`    |S     |V
.3+|1OP  .3+|  2      |130     |`82`    |`10000010`    |S     |L    .3+|   .3+| * .3+| * .3+| xref:15-opcodes.adoc#get_child[`*get_child*`] object -> (result) ?(label)
                     >|146    <|`92`    |`10010010`    |S     |S
                     >|162    <|`a2`    |`10100010`    |S     |V
.3+|1OP  .3+|  3      |131     |`83`    |`10000011`    |S     |L    .3+|   .3+| * .3+|   .3+| xref:15-opcodes.adoc#get_parent[`*get_parent*`] object -> (result)
                     >|147    <|`93`    |`10010011`    |S     |S
                     >|163    <|`a3`    |`10100011`    |S     |V
.3+|1OP  .3+|  4      |132     |`84`    |`10000100`    |S     |L    .3+|   .3+| * .3+|   .3+| xref:15-opcodes.adoc#get_prop_len[`*get_prop_len*`] property-address -> (result)
                     >|148    <|`94`    |`10010100`    |S     |S
                     >|164    <|`a4`    |`10100100`    |S     |V
.3+|1OP  .3+|  5      |133     |`85`    |`10000101`    |S     |L    .3+|   .3+|   .3+|   .3+| xref:15-opcodes.adoc#inc[`*inc*`] (variable)
                     >|149    <|`95`    |`10010101`    |S     |S
                     >|165    <|`a5`    |`10100101`    |S     |V
.3+|1OP  .3+|  6      |134     |`86`    |`10000110`    |S     |L    .3+|   .3+|   .3+|   .3+| xref:15-opcodes.adoc#dec[`*dec*`] (variable)
                     >|150    <|`96`    |`10010110`    |S     |S
                     >|166    <|`a6`    |`10100110`    |S     |V
.3+|1OP  .3+|  7      |135     |`87`    |`10000111`    |S     |L    .3+|   .3+|   .3+|   .3+| xref:15-opcodes.adoc#print_addr[`*print_addr*`] byte-address-of-string
                     >|151    <|`97`    |`10010111`    |S     |S
                     >|167    <|`a7`    |`10100111`    |S     |V
.3+|1OP  .3+|  8      |136     |`88`    |`10001000`    |S     |L    .3+| 4 .3+| * .3+|   .3+| xref:15-opcodes.adoc#call_1s[`*call_1s*`] routine -> (result)
                     >|152    <|`98`    |`10011000`    |S     |S
                     >|168    <|`a8`    |`10101000`    |S     |V
.3+|1OP  .3+|  9      |137     |`89`    |`10001001`    |S     |L    .3+|   .3+|   .3+|   .3+| xref:15-opcodes.adoc#remove_obj[`*remove_obj*`] object
                     >|153    <|`99`    |`10011001`    |S     |S
                     >|169    <|`a9`    |`10101001`    |S     |V
.3+|1OP  .3+| 10      |138     |`8a`    |`10001010`    |S     |L    .3+|   .3+|   .3+|   .3+| xref:15-opcodes.adoc#print_obj[`*print_obj*`] object
                     >|154    <|`9a`    |`10011010`    |S     |S
                     >|170    <|`aa`    |`10101010`    |S     |V
.3+|1OP  .3+| 11      |139     |`8b`    |`10001011`    |S     |L    .3+|   .3+|   .3+|   .3+| xref:15-opcodes.adoc#ret[`*ret*`] value
                     >|155    <|`9b`    |`10011011`    |S     |S
                     >|171    <|`ab`    |`10101011`    |S     |V
.3+|1OP  .3+| 12      |140     |`8c`    |`10001100`    |S     |L    .3+|   .3+|   .3+|   .3+| xref:15-opcodes.adoc#jump[`*jump*`] ?(label)
                     >|156    <|`9c`    |`10011100`    |S     |S
                     >|172    <|`ac`    |`10101100`    |S     |V
.3+|1OP  .3+| 13      |141     |`8d`    |`10001101`    |S     |L    .3+|   .3+|   .3+|   .3+| xref:15-opcodes.adoc#print_paddr[`*print_paddr*`] packed-address-of-string
                     >|157    <|`9d`    |`10011101`    |S     |S
                     >|173    <|`ad`    |`10101101`    |S     |V
.3+|1OP  .3+| 14      |142     |`8e`    |`10001110`    |S     |L    .3+|   .3+| * .3+|   .3+| xref:15-opcodes.adoc#load[`*load*`] (variable) -> (result)
                     >|158    <|`9e`    |`10011110`    |S     |S
                     >|174    <|`ae`    |`10101110`    |S     |V
.3+|1OP  .3+| 15      |143     |`8f`    |`10001111`    |S     |L         | 1/4  | *    |      | xref:15-opcodes.adoc#not[`*not*`] value -> (result)
                     >|159    <|`9f`    |`10011111`    |S     |S     .2+^| 5 .2+|   .2+|   .2+<| xref:15-opcodes.adoc#call_1n[`*call_1n*`] routine
                     >|175    <|`af`    |`10101111`    |S     |V
11+| *_2OP opcodes_*
   |*Count* |*Num*    |*Dec.*  |*Hex*   |*Binary*     |*Form*|*Args*  |*V*|*St*|*Br*|*Instruction and syntax*
.5+|2OP  .5+|  0      |  0     |`00`    |`00000000`    |L     |S,S  .5+| ― .5+| ― .5+| ― .5+| ―
                     >| 32    <|`20`    |`00100000`    |L     |S,V
                     >| 64    <|`40`    |`01000000`    |L     |V,S
                     >| 96    <|`60`    |`01100000`    |L     |V,V
                     >|192    <|`c0`    |`11000000`    |V     |?
.5+|2OP  .5+|  1      |  1     |`01`    |`00000001`    |L     |S,S  .5+|   .5+|   .5+| * .5+| xref:15-opcodes.adoc#je[`*je*`] a b ?(label)
                     >| 33    <|`21`    |`00100001`    |L     |S,V
                     >| 65    <|`41`    |`01000001`    |L     |V,S
                     >| 97    <|`61`    |`01100001`    |L     |V,V
                     >|193    <|`c1`    |`11000001`    |V     |?
.5+|2OP  .5+|  2      |  2     |`02`    |`00000010`    |L     |S,S  .5+|   .5+|   .5+| * .5+| xref:15-opcodes.adoc#jl[`*jl*`] a b ?(label)
                     >| 34    <|`22`    |`00100010`    |L     |S,V
                     >| 66    <|`42`    |`01000010`    |L     |V,S
                     >| 98    <|`62`    |`01100010`    |L     |V,V
                     >|194    <|`c2`    |`11000010`    |V     |?
.5+|2OP  .5+|  3      |  3     |`03`    |`00000011`    |L     |S,S  .5+|   .5+|   .5+| * .5+| xref:15-opcodes.adoc#jg[`*jg*`] a b ?(label)
                     >| 35    <|`23`    |`00100011`    |L     |S,V
                     >| 67    <|`43`    |`01000011`    |L     |V,S
                     >| 99    <|`63`    |`01100011`    |L     |V,V
                     >|195    <|`c3`    |`11000011`    |V     |?
.5+|2OP  .5+|  4      |  4     |`04`    |`00000100`    |L     |S,S  .5+|   .5+|   .5+| * .5+| xref:15-opcodes.adoc#dec_chk[`*dec_chk*`] (variable) value ?(label)
                     >| 36    <|`24`    |`00100100`    |L     |S,V
                     >| 68    <|`44`    |`01000100`    |L     |V,S
                     >|100    <|`64`    |`01100100`    |L     |V,V
                     >|196    <|`c4`    |`11000100`    |V     |?
.5+|2OP  .5+|  5      |  5     |`05`    |`00000101`    |L     |S,S  .5+|   .5+|   .5+| * .5+| xref:15-opcodes.adoc#inc_chk[`*inc_chk*`] (variable) value ?(label)
                     >| 37    <|`25`    |`00100101`    |L     |S,V
                     >| 69    <|`45`    |`01000101`    |L     |V,S
                     >|101    <|`65`    |`01100101`    |L     |V,V
                     >|197    <|`c5`    |`11000101`    |V     |?
.5+|2OP  .5+|  6      |  6     |`06`    |`00000110`    |L     |S,S  .5+|   .5+|   .5+| * .5+| xref:15-opcodes.adoc#jin[`*jin*`] obj1 obj2 ?(label)
                     >| 38    <|`26`    |`00100110`    |L     |S,V
                     >| 70    <|`46`    |`01000110`    |L     |V,S
                     >|102    <|`66`    |`01100110`    |L     |V,V
                     >|198    <|`c6`    |`11000110`    |V     |?
.5+|2OP  .5+|  7      |  7     |`07`    |`00000111`    |L     |S,S  .5+|   .5+|   .5+| * .5+| xref:15-opcodes.adoc#test[`*test*`] bitmap flags ?(label)
                     >| 39    <|`27`    |`00100111`    |L     |S,V
                     >| 71    <|`47`    |`01000111`    |L     |V,S
                     >|103    <|`67`    |`01100111`    |L     |V,V
                     >|199    <|`c7`    |`11000111`    |V     |?
.5+|2OP  .5+|  8      |  8     |`08`    |`00001000`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#or[`*or*`] a b -> (result)
                     >| 40    <|`28`    |`00101000`    |L     |S,V
                     >| 72    <|`48`    |`01001000`    |L     |V,S
                     >|104    <|`68`    |`01101000`    |L     |V,V
                     >|200    <|`c8`    |`11001000`    |V     |?
.5+|2OP  .5+|  9      |  9     |`09`    |`00001001`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#and[`*and*`] a b -> (result)
                     >| 41    <|`29`    |`00101001`    |L     |S,V
                     >| 73    <|`49`    |`01001001`    |L     |V,S
                     >|105    <|`69`    |`01101001`    |L     |V,V
                     >|201    <|`c9`    |`11001001`    |V     |?
.5+|2OP  .5+| 10      | 10     |`0a`    |`00001010`    |L     |S,S  .5+|   .5+|   .5+| * .5+| xref:15-opcodes.adoc#test_attr[`*test_attr*`] object attribute ?(label)
                     >| 42    <|`2a`    |`00101010`    |L     |S,V
                     >| 74    <|`4a`    |`01001010`    |L     |V,S
                     >|106    <|`6a`    |`01101010`    |L     |V,V
                     >|202    <|`ca`    |`11001010`    |V     |?
.5+|2OP  .5+| 11      | 11     |`0b`    |`00001011`    |L     |S,S  .5+|   .5+|   .5+|   .5+| xref:15-opcodes.adoc#set_attr[`*set_attr*`] object attribute
                     >| 43    <|`2b`    |`00101011`    |L     |S,V
                     >| 75    <|`4b`    |`01001011`    |L     |V,S
                     >|107    <|`6b`    |`01101011`    |L     |V,V
                     >|203    <|`cb`    |`11001011`    |V     |?
.5+|2OP  .5+| 12      | 12     |`0c`    |`00001100`    |L     |S,S  .5+|   .5+|   .5+|   .5+| xref:15-opcodes.adoc#clear_attr[`*clear_attr*`] object attribute
                     >| 44    <|`2c`    |`00101100`    |L     |S,V
                     >| 76    <|`4c`    |`01001100`    |L     |V,S
                     >|108    <|`6c`    |`01101100`    |L     |V,V
                     >|204    <|`cc`    |`11001100`    |V     |?
.5+|2OP  .5+| 13      | 13     |`0d`    |`00001101`    |L     |S,S  .5+|   .5+|   .5+|   .5+| xref:15-opcodes.adoc#store[`*store*`] (variable) value
                     >| 45    <|`2d`    |`00101101`    |L     |S,V
                     >| 77    <|`4d`    |`01001101`    |L     |V,S
                     >|109    <|`6d`    |`01101101`    |L     |V,V
                     >|205    <|`cd`    |`11001101`    |V     |?
.5+|2OP  .5+| 14      | 14     |`0e`    |`00001110`    |L     |S,S  .5+|   .5+|   .5+|   .5+| xref:15-opcodes.adoc#insert_obj[`*insert_obj*`] object destination
                     >| 46    <|`2e`    |`00101110`    |L     |S,V
                     >| 78    <|`4e`    |`01001110`    |L     |V,S
                     >|110    <|`6e`    |`01101110`    |L     |V,V
                     >|206    <|`ce`    |`11001110`    |V     |?
.5+|2OP  .5+| 15      | 15     |`0f`    |`00001111`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#loadw[`*loadw*`] array word-index -> (result)
                     >| 47    <|`2f`    |`00101111`    |L     |S,V
                     >| 79    <|`4f`    |`01001111`    |L     |V,S
                     >|111    <|`6f`    |`01101111`    |L     |V,V
                     >|207    <|`cf`    |`11001111`    |V     |?
   |*Count* |*Num*    |*Dec.*  |*Hex*   |*Binary*     |*Form*|*Args*  |*V*|*St*|*Br*|*Instruction and syntax*
.5+|2OP  .5+| 16      | 16     |`10`    |`00010000`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#loadb[`*loadb*`] array byte-index -> (result)
                     >| 48    <|`30`    |`00110000`    |L     |S,V
                     >| 80    <|`50`    |`01010000`    |L     |V,S
                     >|112    <|`70`    |`01110000`    |L     |V,V
                     >|208    <|`d0`    |`11010000`    |V     |?
.5+|2OP  .5+| 17      | 17     |`11`    |`00010001`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#get_prop[`*get_prop*`] object property -> (result)
                     >| 49    <|`31`    |`00110001`    |L     |S,V
                     >| 81    <|`51`    |`01010001`    |L     |V,S
                     >|113    <|`71`    |`01110001`    |L     |V,V
                     >|209    <|`d1`    |`11010001`    |V     |?
.5+|2OP  .5+| 18      | 18     |`12`    |`00010010`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#get_prop_addr[`*get_prop_addr*`] object property -> (result)
                     >| 50    <|`32`    |`00110010`    |L     |S,V
                     >| 82    <|`52`    |`01010010`    |L     |V,S
                     >|114    <|`72`    |`01110010`    |L     |V,V
                     >|210    <|`d2`    |`11010010`    |V     |?
.5+|2OP  .5+| 19      | 19     |`13`    |`00010011`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#get_next_prop[`*get_next_prop*`] object property -> (result)
                     >| 51    <|`33`    |`00110011`    |L     |S,V
                     >| 83    <|`53`    |`01010011`    |L     |V,S
                     >|115    <|`73`    |`01110011`    |L     |V,V
                     >|211    <|`d3`    |`11010011`    |V     |?
.5+|2OP  .5+| 20      | 20     |`14`    |`00010100`    |L     |S,S .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#add[`*add*`] a b -> (result)
                     >| 52    <|`34`    |`00110100`    |L     |S,V
                     >| 84    <|`54`    |`01010100`    |L     |V,S
                     >|116    <|`74`    |`01110100`    |L     |V,V
                     >|212    <|`d4`    |`11010100`    |V     |?
.5+|2OP  .5+| 21      | 21     |`15`    |`00010101`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#sub[`*sub*`] a b -> (result)
                     >| 53    <|`35`    |`00110101`    |L     |S,V
                     >| 85    <|`55`    |`01010101`    |L     |V,S
                     >|117    <|`75`    |`01110101`    |L     |V,V
                     >|213    <|`d5`    |`11010101`    |V     |?
.5+|2OP  .5+| 22      | 22     |`16`    |`00010110`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#mul[`*mul*`] a b -> (result)
                     >| 54    <|`36`    |`00110110`    |L     |S,V
                     >| 86    <|`56`    |`01010110`    |L     |V,S
                     >|118    <|`76`    |`01110110`    |L     |V,V
                     >|214    <|`d6`    |`11010110`    |V     |?
.5+|2OP  .5+| 23      | 23     |`17`    |`00010111`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#div[`*div*`] a b -> (result)
                     >| 55    <|`37`    |`00110111`    |L     |S,V
                     >| 87    <|`57`    |`01010111`    |L     |V,S
                     >|119    <|`77`    |`01110111`    |L     |V,V
                     >|215    <|`d7`    |`11010111`    |V     |?
.5+|2OP  .5+| 24      | 24     |`18`    |`00011000`    |L     |S,S  .5+|   .5+| * .5+|   .5+| xref:15-opcodes.adoc#mod[`*mod*`] a b -> (result)
                     >| 56    <|`38`    |`00111000`    |L     |S,V
                     >| 88    <|`58`    |`01011000`    |L     |V,S
                     >|120    <|`78`    |`01111000`    |L     |V,V
                     >|216    <|`d8`    |`11011000`    |V     |?
.5+|2OP  .5+| 25      | 25     |`19`    |`00011001`    |L     |S,S  .5+| 4 .5+| * .5+|   .5+| xref:15-opcodes.adoc#call_2s[`*call_2s*`] routine arg1 -> (result)
                     >| 57    <|`39`    |`00111001`    |L     |S,V
                     >| 89    <|`59`    |`01011001`    |L     |V,S
                     >|121    <|`79`    |`01111001`    |L     |V,V
                     >|217    <|`d9`    |`11011001`    |V     |?
.5+|2OP  .5+| 26      | 26     |`1a`    |`00011010`    |L     |S,S  .5+| 5 .5+|   .5+|   .5+| xref:15-opcodes.adoc#call_2n[`*call_2n*`] routine arg1
                     >| 58    <|`3a`    |`00111010`    |L     |S,V
                     >| 90    <|`5a`    |`01011010`    |L     |V,S
                     >|122    <|`7a`    |`01111010`    |L     |V,V
                     >|218    <|`da`    |`11011010`    |V     |?
.5+|2OP  .5+| 27      | 27     |`1b`    |`00011011`    |L     |S,S     | 5    |      |      | xref:15-opcodes.adoc#set_colour[`*set_colour*`] foreground background
                     >| 59    <|`3b`    |`00111011`    |L     |S,V .4+^| 6 .4+|   .4+|   .4+<| xref:15-opcodes.adoc#set_colour[`*set_colour*`] foreground background window
                     >| 91    <|`5b`    |`01011011`    |L     |V,S
                     >|123    <|`7b`    |`01111011`    |L     |V,V
                     >|219    <|`db`    |`11011011`    |V     |?
.5+|2OP  .5+| 28      | 28     |`1c`    |`00011100`    |L     |S,S  .5+|5/6 .5+|   .5+|   .5+| xref:15-opcodes.adoc#throw[`*throw*`] value stack-frame
                     >| 60    <|`3c`    |`00111100`    |L     |S,V
                     >| 92    <|`5c`    |`01011100`    |L     |V,S
                     >|124    <|`7c`    |`01111100`    |L     |V,V
                     >|220    <|`dc`    |`11011100`    |V     |?
.5+|2OP  .5+| 29      | 29     |`1d`    |`00011101`    |L     |S,S  .5+| ― .5+| ― .5+| ― .5+| ―
                     >| 61    <|`3d`    |`00111101`    |L     |S,V
                     >| 93    <|`5d`    |`01011101`    |L     |V,S
                     >|125    <|`7d`    |`01111101`    |L     |V,V
                     >|221    <|`dd`    |`11011101`    |V     |?
.5+|2OP  .5+| 30      | 30     |`1e`    |`00011110`    |L     |S,S  .5+| ― .5+| ― .5+| ― .5+| ―
                     >| 62    <|`3e`    |`00111110`    |L     |S,V
                     >| 94    <|`5e`    |`01011110`    |L     |V,S
                     >|126    <|`7e`    |`01111110`    |L     |V,V
                     >|222    <|`de`    |`11011110`    |V     |?
.5+|2OP  .5+| 31      | 31     |`1f`    |`00011111`    |L     |S,S  .5+| ― .5+| ― .5+| ― .5+| ―
                     >| 63    <|`3f`    |`00111111`    |L     |S,V
                     >| 95    <|`5f`    |`01011111`    |L     |V,S
                     >|127    <|`7f`    |`01111111`    |L     |V,V
                     >|223    <|`df`    |`11011111`    |V     |?
11+| *_VAR opcodes_*
   |*Count* |*Num*    |*Dec.*  |*Hex*   |*Binary*     |*Form*|*Args*  |*V*|*St*|*Br*|*Instruction and syntax*
.2+|VAR  .2+|  0   .2+|224  .2+|`e0` .2+|`11100000` .2+|V  .2+|?       | 1 | * |   | xref:15-opcodes.adoc#call[`*call*`] routine _…​0 to 3 args…​_ -> (result)
                                                                      ^| 4 |   |   | xref:15-opcodes.adoc#call_vs[`*call_vs*`] routine _…​0 to 3 args…​_ -> (result)
   |VAR     |  1      |225     |`e1`    |`11100001`    |V     |?       |   |   |   | xref:15-opcodes.adoc#storew[`*storew*`] array word-index value
   |VAR     |  2      |226     |`e2`    |`11100010`    |V     |?       |   |   |   | xref:15-opcodes.adoc#storeb[`*storeb*`] array byte-index value
   |VAR     |  3      |227     |`e3`    |`11100011`    |V     |?       |   |   |   | xref:15-opcodes.adoc#put_prop[`*put_prop*`] object property value
.3+|VAR  .3+|  4   .3+|228  .3+|`e4` .3+|`11100100` .3+|V  .3+|?       | 1 |   |   | xref:15-opcodes.adoc#sread[`*sread*`] text parse
                                                                      ^| 4 |   |   | xref:15-opcodes.adoc#sread[`*sread*`] text parse time routine
                                                                      ^| 5 ^|* |   | xref:15-opcodes.adoc#aread[`*aread*`] text parse time routine -> (result)
   |VAR     |  5      |229     |`e5`    |`11100101`    |V     |?       |   |   |   | xref:15-opcodes.adoc#print_char[`*print_char*`] output-character-code
   |VAR     |  6      |230     |`e6`    |`11100110`    |V     |?       |   |   |   | xref:15-opcodes.adoc#print_num[`*print_num*`] value
   |VAR     |  7      |231     |`e7`    |`11100111`    |V     |?       |   | * |   | xref:15-opcodes.adoc#random[`*random*`] range -> (result)
   |VAR     |  8      |232     |`e8`    |`11101000`    |V     |?       |   |   |   | xref:15-opcodes.adoc#push[`*push*`] value
.2+|VAR  .2+|  9   .2+|233  .2+|`e9` .2+|`11101001` .2+|V  .2+|?       | 1 |   |   | xref:15-opcodes.adoc#pull[`*pull*`] (variable)
                                                                      ^| 6 ^|* |   | xref:15-opcodes.adoc#pull[`*pull*`] stack -> (result)
   |VAR     | 10      |234     |`ea`    |`11101010`    |V     |?       | 3 |   |   | xref:15-opcodes.adoc#split_window[`*split_window*`] lines
   |VAR     | 11      |235     |`eb`    |`11101011`    |V     |?       | 3 |   |   | xref:15-opcodes.adoc#set_window[`*set_window*`] window
   |VAR     | 12      |236     |`ec`    |`11101100`    |V     |?       | 4 | * |   | xref:15-opcodes.adoc#call_vs2[`*call_vs2*`] routine _…​0 to 7 args…​_ -> (result)
   |VAR     | 13      |237     |`ed`    |`11101101`    |V     |?       | 4 |   |   | xref:15-opcodes.adoc#erase_window[`*erase_window*`] window
.2+|VAR  .2+| 14   .2+|238  .2+|`ee` .2+|`11101110` .2+|V  .2+|?       |4/-|   |   | xref:15-opcodes.adoc#erase_line[`*erase_line*`] value
                                                                      ^| 6 |   |   | xref:15-opcodes.adoc#erase_line[`*erase_line*`] pixels
.2+|VAR  .2+| 15   .2+|239  .2+|`ef` .2+|`11101111` .2+|V  .2+|?       | 4 |   |   | xref:15-opcodes.adoc#set_cursor[`*set_cursor*`] line column
                                                                      ^| 6 |   |   | xref:15-opcodes.adoc#set_cursor[`*set_cursor*`] line column window
   |VAR     | 16      |240     |`f0`    |`11110000`    |V     |?       |4/6|   |   | xref:15-opcodes.adoc#get_cursor[`*get_cursor*`] array
   |VAR     | 17      |241     |`f1`    |`11110001`    |V     |?       | 4 |   |   | xref:15-opcodes.adoc#set_text_style[`*set_text_style*`] style
   |VAR     | 18      |242     |`f2`    |`11110010`    |V     |?       | 4 |   |   | xref:15-opcodes.adoc#buffer_mode[`*buffer_mode*`] flag
.3+|VAR  .3+| 19   .3+|243  .3+|`f3` .3+|`11110011` .3+|V  .3+|?       | 3 |   |   | xref:15-opcodes.adoc#output_stream[`*output_stream*`] number
                                                                      ^| 5 |   |   | xref:15-opcodes.adoc#output_stream[`*output_stream*`] number table
                                                                      ^| 6 |   |   | xref:15-opcodes.adoc#output_stream[`*output_stream*`] number table width
   |VAR     | 20      |244     |`f4`    |`11110100`    |V     |?       | 3 |   |   | xref:15-opcodes.adoc#input_stream[`*input_stream*`] number
   |VAR     | 21      |245     |`f5`    |`11110101`    |V     |?       |5/3|   |   | xref:15-opcodes.adoc#sound_effect[`*sound_effect*`] number effect volume routine
   |VAR     | 22      |246     |`f6`    |`11110110`    |V     |?       | 4 | * |   | xref:15-opcodes.adoc#read_char[`*read_char*`] 1 time routine -> (result)
   |VAR     | 23      |247     |`f7`    |`11110111`    |V     |?       | 4 | * | * | xref:15-opcodes.adoc#scan_table[`*scan_table*`] x table len form -> (result)
   |VAR     | 24      |248     |`f8`    |`11111000`    |V     |?       |5/6| * |   | xref:15-opcodes.adoc#not[`*not*`] value -> (result)
   |VAR     | 25      |249     |`f9`    |`11111001`    |V     |?       | 5 |   |   | xref:15-opcodes.adoc#call_vn[`*call_vn*`] routine _…​up to 3 args…​_
   |VAR     | 26      |250     |`fa`    |`11111010`    |V     |?       | 5 |   |   | xref:15-opcodes.adoc#call_vn2[`*call_vn2*`] routine _…​up to 7 args…​_
   |VAR     | 27      |251     |`fb`    |`11111011`    |V     |?       | 5 |   |   | xref:15-opcodes.adoc#tokenise[`*tokenise*`] text parse dictionary flag
   |VAR     | 28      |252     |`fc`    |`11111100`    |V     |?       | 5 |   |   | xref:15-opcodes.adoc#encode_text[`*encode_text*`] zscii-text length from coded-text
   |VAR     | 29      |253     |`fd`    |`11111101`    |V     |?       | 5 |   |   | xref:15-opcodes.adoc#copy_table[`*copy_table*`] first second size 
   |VAR     | 30      |254     |`fe`    |`11111110`    |V     |?       | 5 |   |   | xref:15-opcodes.adoc#print_table[`*print_table*`] zscii-text width height skip
   |VAR     | 31      |255     |`ff`    |`11111111`    |V     |?       | 5 |   | * | xref:15-opcodes.adoc#check_arg_count[`*check_arg_count*`] argument-number
11+| *_EXT opcodes_*
   |*Count* |*Num*    |*Dec.*  |*Hex*   |*Binary*     |*Form*|*Args*  |*V*|*St*|*Br*|*Instruction and syntax*
   |EXT     |  ―      |190     |`be`    |`10111110`    |E     |        |   |   |   | _Extended opcode sentinel value_
   |EXT     |  0      |  0     |`00`    |`00000000`    |E     |?       | 5 | * |   | xref:15-opcodes.adoc#save[`*save*`] table bytes name prompt -> (result)
   |EXT     |  1      |  1     |`01`    |`00000001`    |E     |?       | 5 | * |   | xref:15-opcodes.adoc#restore[`*restore*`] table bytes name prompt -> (result)
   |EXT     |  2      |  2     |`02`    |`00000010`    |E     |?       | 5 | * |   | xref:15-opcodes.adoc#log_shift[`*log_shift*`] number places -> (result)
   |EXT     |  3      |  3     |`03`    |`00000011`    |E     |?       |5/-| * |   | xref:15-opcodes.adoc#art_shift[`*art_shift*`] number places -> (result)
.2+|EXT  .2+|  4   .2+|  4  .2+|`04` .2+|`00000100` .2+|E  .2+|?       | 5 | * |   | xref:15-opcodes.adoc#set_font[`*set_font*`] font -> (result)
                                                                      ^|6/- ^|*|   | xref:15-opcodes.adoc#set_font[`*set_font*`] font window -> (result)
   |EXT     |  5      |  5     |`05`    |`00000101`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#draw_picture[`*draw_picture*`] picture-number y x
   |EXT     |  6      |  6     |`06`    |`00000110`    |E     |?       | 6 |   | * | xref:15-opcodes.adoc#picture_data[`*picture_data*`] picture-number array ?(label)
   |EXT     |  7      |  7     |`07`    |`00000111`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#erase_picture[`*erase_picture*`] picture-number y x
   |EXT     |  8      |  8     |`08`    |`00001000`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#set_margins[`*set_margins*`] left right window
   |EXT     |  9      |  9     |`09`    |`00001001`    |E     |?       | 5 | * |   | xref:15-opcodes.adoc#save_undo[`*save_undo*`] -> (result)
   |EXT     | 10      | 10     |`0a`    |`00001010`    |E     |?       | 5 | * |   | xref:15-opcodes.adoc#restore_undo[`*restore_undo*`] -> (result)
   |EXT     | 11      | 11     |`0b`    |`00001011`    |E     |?       |5/*|   |   | xref:15-opcodes.adoc#print_unicode[`*print_unicode*`] char-number
   |EXT     | 12      | 12     |`0c`    |`00001100`    |E     |?       |5/*|   |   | xref:15-opcodes.adoc#check_unicode[`*check_unicode*`] char-number -> (result)
.2+|EXT  .2+| 13   .2+| 13  .2+|`0d` .2+|`00001101` .2+|E  .2+|?       |5/*|   |   | xref:15-opcodes.adoc#set_true_colour[`*set_true_colour*`] foreground background
                                                                      ^|6/*|   |   | xref:15-opcodes.adoc#set_true_colour[`*set_true_colour*`] foreground background window
   |EXT     | ―       | 14     |`0e`    |`00001110`    |E     |?       |   |   |   | ―
   |EXT     | ―       | 15     |`0f`    |`00001111`    |E     |?       |   |   |   | ―
   |EXT     | 16      | 16     |`10`    |`00010000`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#move_window[`*move_window*`] window y x
   |EXT     | 17      | 17     |`11`    |`00010001`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#window_size[`*window_size*`] window y x
   |EXT     | 18      | 18     |`12`    |`00010010`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#window_style[`*window_style*`] window flags operation
   |EXT     | 19      | 19     |`13`    |`00010011`    |E     |?       | 6 | * |   | xref:15-opcodes.adoc#get_wind_prop[`*get_wind_prop*`] window property-number -> (result)
   |EXT     | 20      | 20     |`14`    |`00010100`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#scroll_window[`*scroll_window*`] window pixels
   |EXT     | 21      | 21     |`15`    |`00010101`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#pop_stack[`*pop_stack*`] items stack
   |EXT     | 22      | 22     |`16`    |`00010110`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#read_mouse[`*read_mouse*`] array
   |EXT     | 23      | 23     |`17`    |`00010111`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#mouse_window[`*mouse_window*`] window
   |EXT     | 24      | 24     |`18`    |`00011000`    |E     |?       | 6 |   | * | xref:15-opcodes.adoc#push_stack[`*push_stack*`] value stack ?(label)
   |EXT     | 25      | 25     |`19`    |`00011001`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#put_wind_prop[`*put_wind_prop*`] window property-number value
   |EXT     | 26      | 26     |`1a`    |`00011010`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#print_form[`*print_form*`] formatted-table
   |EXT     | 27      | 27     |`1b`    |`00011011`    |E     |?       | 6 |   | * | xref:15-opcodes.adoc#make_menu[`*make_menu*`] number table ?(label)
   |EXT     | 28      | 28     |`1c`    |`00011100`    |E     |?       | 6 |   |   | xref:15-opcodes.adoc#picture_table[`*picture_table*`] table
   |EXT     | 29      | 29     |`1d`    |`00011101`    |E     |?       |6/*| * |   | xref:15-opcodes.adoc#buffer_screen[`*buffer_screen*`] mode -> (result)
|===
