site:
  title: The Z-Machine Standards Document
  url: https://zspec.jaredreisinger.com
  robots: allow
  keys:
    googleAnalytics: 'G-ZJW7TDDE3W'

content:
  sources:
    - url: .
      branches: HEAD

asciidoc:
  attributes:
    page-pagination: true
    kroki-fetch-diagram: true
    bytefield-defaults: |
      (defattrs :plain {:font-family "inherit" :font-size 14})
      (defattrs :unused [:plain {:font-size 12 :font-style "italic" :fill "hsl(0, 0%, 60%)"}])
      (defattrs :vertical [:plain {:writing-mode "vertical-rl"}])
      (defattrs :v1 {:fill "hsl(120, 50%, 80%)"})
      (defattrs :v2 {:fill "hsl(110, 50%, 80%)"})
      (defattrs :v3 {:fill "hsl(100, 50%, 80%)"})
      (defattrs :v4 {:fill "hsl( 80, 50%, 80%)"})
      (defattrs :v5 {:fill "hsl( 60, 50%, 80%)"})
      (defattrs :v6 {:fill "hsl( 40, 50%, 80%)"})
      (defattrs :vX {:fill "hsl(  0, 50%, 70%)"})
    bitfield-defaults: |
      (def left-margin 1)
      (def box-width 30)
      (def row-height 100)
    # {bytefield-defaults}

  extensions:
    - '@deepsymmetry/asciidoctor-bytefield'
    - asciidoctor-kroki
    - './extensions/date-formatter.js'

antora:
  extensions:
    - '@antora/lunr-extension'

urls:
  html_extension_style: drop
  redirect_facility: netlify

output:
  clean: true
  dir: ./build

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
