site:
  title: The Z-Machine Standards Document
  url: https://zspec.jaredreisinger.com
  robots: allow
  keys:
    googleAnalytics: 'G-ZJW7TDDE3W'

content:
  sources:
    - url: .
      branches: HEAD

asciidoc:
  attributes:
    page-pagination: true
    kroki-fetch-diagram: true
  extensions:
    - '@deepsymmetry/asciidoctor-bytefield'
    - asciidoctor-kroki
    - './extensions/date-formatter.js'

antora:
  extensions:
    - '@antora/lunr-extension'

urls:
  html_extension_style: drop
  redirect_facility: netlify

output:
  clean: true
  dir: ./build

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
