site:
  title: The Z-Machine Standard
  url: https://zspec.jaredreisinger.com

content:
  sources:
    - url: .
      branches: HEAD

asciidoc:
  attributes:
    page-pagination: true

urls:
  html_extension_style: drop
  redirect_facility: netlify

output:
  clean: true
  dir: ./build

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
